apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-demo1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      completions : 3
      parallelism : 6
      template:
        metadata :
          labels :
            name : cron-demo1
        spec:
          containers:
          - name: cron-demo1
            image: centos:7
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never

          
