
apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
    - name: my-app-container
      image: my-app-image
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10


# A liveness probe can be configured for a container in a pod, and Kubernetes periodically executes the specified probe action (HTTP request, TCP socket check, or running a command) to determine if the container is still alive. If the probe action fails a certain number of times in a row, Kubernetes will consider the container as unhealthy and take corrective actions, which may include restarting the container.